# Generated by Django 3.1.1 on 2020-10-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_in', models.CharField(max_length=300)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('height', models.FloatField(null=True)),
                ('skin_color', models.CharField(choices=[('Piel muy clara o blanca', 'Piel muy clara o blanca'), ('Piel clara', 'Piel clara'), ('Piel clara intermedia', 'Piel clara intermedia'), ('Piel morena o media', 'Piel morena o media'), ('Piel oscura o marrón', 'Piel oscura o marrón'), ('Piel muy oscura o negra', 'Piel muy oscura o negra')], max_length=100)),
                ('eye_color', models.CharField(max_length=50, null=True)),
                ('clothes', models.CharField(max_length=500, null=True)),
                ('unique_characteristics', models.CharField(max_length=300, null=True)),
                ('last_seen_in', models.CharField(max_length=300, null=True)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.CharField(max_length=200)),
                ('contact_full_name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
    ]
