# Generated by Django 3.1.1 on 2020-10-17 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='clue_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kaltsapp.missingperson'),
        ),
    ]
