# Generated by Django 3.1.1 on 2020-10-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0002_clue_clue_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='date_and_time',
            field=models.DateTimeField(),
        ),
    ]
