# Generated by Django 3.1.1 on 2020-10-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0003_auto_20201017_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='date_and_time',
            field=models.DateTimeField(),
        ),
    ]
