# Generated by Django 3.1.1 on 2020-10-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0004_auto_20201017_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='hair_color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
