# Generated by Django 3.1.1 on 2020-11-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0005_auto_20201022_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Female', 'Female')], max_length=100, null=True),
        ),
    ]
