# Generated by Django 3.1.1 on 2020-11-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0008_auto_20201103_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='clothes',
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Female', 'Female')], default='Género', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='skin_color',
            field=models.CharField(choices=[('Piel muy clara o blanca', 'Piel muy clara o blanca'), ('Piel clara', 'Piel clara'), ('Piel clara intermedia', 'Piel clara intermedia'), ('Piel morena o media', 'Piel morena o media'), ('Piel oscura o marrón', 'Piel oscura o marrón'), ('Piel muy oscura o negra', 'Piel muy oscura o negra')], default='Color de piel', max_length=100),
        ),
    ]
