# Generated by Django 3.1.1 on 2020-11-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0009_auto_20201104_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='person_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
