# Generated by Django 3.1.1 on 2020-11-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0010_missingperson_person_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='person_image',
        ),
    ]
