# Generated by Django 3.1.1 on 2020-11-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0011_remove_missingperson_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='person_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
