# Generated by Django 3.1.1 on 2020-11-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0012_missingperson_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='person_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
