# Generated by Django 3.1.1 on 2020-11-16 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kaltsapp', '0013_auto_20201106_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='contact_full_name',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
