# Generated by Django 3.1.1 on 2020-11-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0014_auto_20201116_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='date_and_time',
            field=models.DateTimeField(null=True),
        ),
    ]
