# Generated by Django 3.1.1 on 2020-11-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0015_auto_20201116_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='date_and_time',
            field=models.DateTimeField(null=True),
        ),
    ]
