# Generated by Django 3.1.1 on 2020-11-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsapp', '0018_auto_20201122_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Municipio',
        ),
        migrations.RenameField(
            model_name='missingperson',
            old_name='city',
            new_name='municipio',
        ),
        migrations.AddField(
            model_name='clue',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaltsapp.municipio'),
        ),
        migrations.AddField(
            model_name='clue',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaltsapp.state'),
        ),
    ]
